"""
Signal A — LLM Semantic Classifier
===================================
Sends the submitted text to Groq (llama-3.3-70b-versatile) with a structured
prompt and extracts:

  verdict     : "ai" | "human"
  raw_score   : float 0.0–1.0
                0.0 = confident human, 1.0 = confident AI
  reasoning_excerpt : first 200 chars of the model's explanation

The model is asked to return *only* a JSON object — no prose wrapper.
raw_score is produced explicitly by the model, not derived from token
probabilities, so it reflects the model's stated confidence directly.

Blind spots documented in planning.md §2 Signal A.
"""

import json
import os
import re
from typing import TypedDict

import requests


# ── Types ──────────────────────────────────────────────────────────────────

class LLMSignalResult(TypedDict):
    signal: str          # always "llm_classifier"
    verdict: str         # "ai" | "human"
    raw_score: float     # 0.0 (human) → 1.0 (AI)
    reasoning_excerpt: str


# ── Prompt ─────────────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """\
You are an expert writing analyst. Your task is to assess whether a piece of
text was written by a human or generated by an AI language model.

Evaluate the text on these dimensions:
- Voice authenticity: does it have genuine idiosyncrasy, or smooth uniformity?
- Structural risk-taking: unexpected turns, self-correction, unresolved tension?
- Phrasing: are metaphors earned and specific, or generic and safe?
- Cadence: does sentence rhythm reflect thought, or optimised readability?

You MUST respond with ONLY a valid JSON object — no explanation outside it,
no markdown fences, no preamble. The object must have exactly these keys:

{
  "verdict": "ai" or "human",
  "raw_score": <float between 0.0 and 1.0>,
  "reasoning": "<one or two sentences explaining your main signal>"
}

raw_score meaning:
  0.0 = you are highly confident this is human-written
  0.5 = genuine uncertainty
  1.0 = you are highly confident this is AI-generated

Be calibrated: reserve scores above 0.85 or below 0.15 for clear-cut cases.
"""

_USER_TEMPLATE = """\
Analyse the following text for attribution:

---
{text}
---

Respond with the JSON object only.
"""


# ── Groq API call ──────────────────────────────────────────────────────────

_GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
_MODEL = "llama-3.3-70b-versatile"
_MAX_TOKENS = 256
_TEMPERATURE = 0.1   # low temperature for consistent, calibrated output


def run_llm_classifier(text: str) -> LLMSignalResult:
    """
    Call the Groq LLM classifier and return a structured signal result.

    Raises RuntimeError if the API call fails or the response cannot be parsed.
    Callers should catch RuntimeError and handle gracefully (e.g. mark signal
    as unavailable rather than crashing the whole pipeline).
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY environment variable is not set. "
            "Add it to your .env file."
        )

    payload = {
        "model": _MODEL,
        "temperature": _TEMPERATURE,
        "max_tokens": _MAX_TOKENS,
        "messages": [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
        ],
    }

    try:
        response = requests.post(
            _GROQ_API_URL,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=30,
        )
        response.raise_for_status()
    except requests.exceptions.Timeout:
        raise RuntimeError("Groq API request timed out after 30 seconds.")
    except requests.exceptions.RequestException as exc:
        raise RuntimeError(f"Groq API request failed: {exc}") from exc

    raw_content = response.json()["choices"][0]["message"]["content"].strip()

    return _parse_llm_response(raw_content)


# ── Response parsing ───────────────────────────────────────────────────────

def _parse_llm_response(raw: str) -> LLMSignalResult:
    """
    Parse the model's JSON response into a LLMSignalResult.

    The model is instructed to return bare JSON, but we defensively strip
    markdown fences in case it ignores the instruction.
    """
    # Strip ```json ... ``` fences if present
    cleaned = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned).strip()

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Could not parse LLM response as JSON. "
            f"Raw response: {raw[:300]!r}"
        ) from exc

    # Validate required keys
    for key in ("verdict", "raw_score", "reasoning"):
        if key not in data:
            raise RuntimeError(
                f"LLM response missing required key '{key}'. "
                f"Got: {list(data.keys())}"
            )

    verdict = str(data["verdict"]).lower().strip()
    if verdict not in ("ai", "human"):
        raise RuntimeError(
            f"LLM returned unexpected verdict '{verdict}'. Expected 'ai' or 'human'."
        )

    try:
        raw_score = float(data["raw_score"])
    except (TypeError, ValueError) as exc:
        raise RuntimeError(
            f"LLM raw_score is not a float: {data['raw_score']!r}"
        ) from exc

    # Clamp to [0.0, 1.0] in case the model drifts slightly outside
    raw_score = max(0.0, min(1.0, raw_score))

    reasoning = str(data.get("reasoning", "")).strip()

    return LLMSignalResult(
        signal="llm_classifier",
        verdict=verdict,
        raw_score=raw_score,
        reasoning_excerpt=reasoning[:200],
    )